server:
  port: 8096
spring:
  application:
    name: springboot-knative-demo
  data:
    mongodb:
      host: mongodb
      port: 27017
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      database: ${MONGO_DATABASE}
      authentication-database: admin
